var searchData=
[
  ['filecontext_0',['FileContext',['../class_file_data_1_1_file_context.html',1,'FileData']]],
  ['filecontext_2ecs_1',['FileContext.cs',['../_file_context_8cs.html',1,'']]],
  ['filedata_2',['FileData',['../namespace_file_data.html',1,'']]],
  ['filedata_2eassemblyinfo_2ecs_3',['FileData.AssemblyInfo.cs',['../_file_data_8_assembly_info_8cs.html',1,'']]],
  ['filedata_2eglobalusings_2eg_2ecs_4',['FileData.GlobalUsings.g.cs',['../_file_data_8_global_usings_8g_8cs.html',1,'']]],
  ['filedata_3a_3adaos_5',['DAOs',['../namespace_file_data_1_1_d_a_os.html',1,'FileData']]],
  ['font_6',['font',['../md__blazor_web_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md35',1,'Using Open Iconic&apos;s Icon Font...'],['../md__blazor_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md21',1,'Using Open Iconic&apos;s Icon Font...'],['../md__blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md7',1,'Using Open Iconic&apos;s Icon Font...']]],
  ['fonts_7',['fonts',['../md__blazor_web_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md41',1,'Fonts'],['../md__blazor_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md27',1,'Fonts'],['../md__blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md13',1,'Fonts']]],
  ['footprint_20mdash_20ready_20to_20use_20with_20bootstrap_20and_20foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_8',['footprint mdash ready to use with bootstrap and foundation a href https: github com iconic open iconic view the collection a',['../md__blazor_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md14',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md__blazor_web_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md28',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md__blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;']]],
  ['for_20code_20samples_20and_20everything_20else_20you_20need_20to_20get_20started_20with_20open_20iconic_20check_20out_20our_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20icons_20a_20and_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20reference_20a_20sections_9',['for code samples and everything else you need to get started with open iconic check out our a href https: github com iconic open iconic icons a and a href https: github com iconic open iconic reference a sections',['../md__blazor_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md17',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.'],['../md__blazor_web_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md31',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.'],['../md__blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md3',1,'For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.']]],
  ['foundation_10',['foundation',['../md__blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md9',1,'…with Foundation'],['../md__blazor_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md23',1,'…with Foundation'],['../md__blazor_web_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md37',1,'…with Foundation']]],
  ['foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_11',['foundation a href https: github com iconic open iconic view the collection a',['../md__blazor_web_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md28',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md__blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;'],['../md__blazor_app_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md14',1,'Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;']]]
];
